"""empty message

Revision ID: 1997668429cd
Revises: fa939c8905fa
Create Date: 2018-05-15 11:38:24.445762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1997668429cd'
down_revision = 'fa939c8905fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspirante', sa.Column('apellidos', sa.String(length=80), nullable=True))
    op.add_column('aspirante', sa.Column('nombres', sa.String(length=80), nullable=True))
    op.drop_column('aspirante', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspirante', sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('aspirante', 'nombres')
    op.drop_column('aspirante', 'apellidos')
    # ### end Alembic commands ###
