"""empty message

Revision ID: b2af0dc412ad
Revises: d15fe8004329
Create Date: 2018-04-15 17:26:37.690219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2af0dc412ad'
down_revision = 'd15fe8004329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('preguntas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encuesta')
    op.drop_table('perfil')
    # ### end Alembic commands ###
