"""empty message

Revision ID: b6b7975d48ad
Revises: 6cf10ba97a49
Create Date: 2019-03-09 16:21:22.928467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b7975d48ad'
down_revision = '6cf10ba97a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aspirante', sa.Integer(), nullable=True),
    sa.Column('id_encuesta', sa.Integer(), nullable=True),
    sa.Column('respuestas', sa.JSON(), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_aspirante'], ['aspirante.id'], ),
    sa.ForeignKeyConstraint(['id_encuesta'], ['encuesta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas')
    # ### end Alembic commands ###
