"""empty message

Revision ID: eb36659e86b6
Revises: 1997668429cd
Create Date: 2018-05-16 01:20:40.358793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb36659e86b6'
down_revision = '1997668429cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspirante', sa.Column('newsletter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aspirante', 'newsletter')
    # ### end Alembic commands ###
