"""empty message

Revision ID: fa939c8905fa
Revises: b2af0dc412ad
Create Date: 2018-04-15 22:58:07.675558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa939c8905fa'
down_revision = 'b2af0dc412ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encuesta', sa.Column('live', sa.Boolean(), nullable=True))
    op.add_column('perfil', sa.Column('live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'live')
    op.drop_column('encuesta', 'live')
    # ### end Alembic commands ###
